# Script to import the data
import json
import h5py
import numpy as np

def import_trx(path):
    """Function that imports a trx file from the path and format it into a dictionnary of dictionnaries
    """
    field_rmv = ['As_smooth_5',
#'S',
#'S_deriv_smooth_5',
#'S_smooth_5',
#'angle_downer_upper_deriv_smooth_5',
#'angle_downer_upper_smooth_5',
#'angle_upper_lower_deriv_smooth_5',
#'angle_upper_lower_smooth_5',
'back',
'back_large',
'back_strong',
'back_weak',
'ball_proba',
'bend_proba',
'cast',
'cast_large',
'cast_strong',
'cast_weak',
'curl_proba',
'd_eff_head_norm_deriv_smooth_5',
'd_eff_head_norm_smooth_5',
'd_eff_tail_norm_deriv_smooth_5',
'd_eff_tail_norm_smooth_5',
'duration_large',
'duration_large_small',
'eig_deriv_smooth_5',
'eig_smooth_5',
'full_path',
'global_state',
#'global_state_large_state',
#'global_state_small_large_state',
#'head_velocity_norm_smooth_5',
'hunch',
'hunch_large',
'hunch_strong',
'hunch_weak',
#'id',
#'larva_length_deriv_smooth_5',
#'larva_length_smooth_5',
'motion_to_u_tail_head_smooth_5',
'motion_to_v_tail_head_smooth_5',
'motion_velocity_norm_smooth_5',
'n_duration',
'n_duration_large',
'n_duration_large_small',
'nb_action',
'nb_action_large',
'nb_action_large_small',
'neuron',
'numero_larva',
#'numero_larva_num',
'pipeline',
'proba_global_state',
'prod_scal_1',
'prod_scal_2',
'protocol',
'roll',
'roll_large',
'roll_strong',
'roll_weak',
'run',
'run_large',
'run_strong',
'run_weak',
'small_motion',
'start_stop',
'start_stop_large',
'start_stop_large_small',
'stimuli',
'stop',
'stop_large',
'stop_strong',
'stop_weak',
'straight_and_light_bend_proba',
'straight_proba',
#'t',
't_start_stop',
't_start_stop_large',
't_start_stop_large_small',
'tail_velocity_norm_smooth_5',
#'x_center',
'x_contour',
#'x_head',
'x_neck',
'x_neck_down',
'x_neck_top',
#'x_spine',
'x_tail',
#'y_center',
'y_contour',
#'y_head',
'y_neck',
'y_neck_down',
'y_neck_top',
#'y_spine',
 'y_tail']

    with h5py.File(path,'r') as f:
        fields = list(f['trx'].keys())
        for rmv in field_rmv :
            fields.remove(rmv)
        trx_extracted = dict() #This will be the list the contains all the larva value -> For each larva it will contains all the fields

        #We take the shape of the actual trx file
        nb_larvae = f['trx'][fields[0]].shape[1]
        print(nb_larvae)
        for i in range(nb_larvae) :
            larva = dict()
            for field in fields :
                ref = f['trx'][field][0][i]
                data = np.array(f[ref])
                data = data.tolist()
                data = data[0] if len(data)==1 else data
                larva[field]=data
            larva["nb_timestep"]=len(data[0])
            print(larva["id"])
            _id = larva.pop("numero_larva_num")
            _id=set(_id)
            print(_id)
            #trx_extracted[] = larva
        f.close()
    trx = dict()
    trx["data"] = trx_extracted
    return trx


###All the fields of the trx file are :
# ['As_smooth_5',
# 'S',
# 'S_deriv_smooth_5',
# 'S_smooth_5',
# 'angle_downer_upper_deriv_smooth_5',
# 'angle_downer_upper_smooth_5',
# 'angle_upper_lower_deriv_smooth_5',
# 'angle_upper_lower_smooth_5',
# 'back',
# 'back_large',
# 'back_strong',
# 'back_weak',
# 'ball_proba',
# 'bend_proba',
# 'cast',
# 'cast_large',
# 'cast_strong',
# 'cast_weak',
# 'curl_proba',
# 'd_eff_head_norm_deriv_smooth_5',
# 'd_eff_head_norm_smooth_5',
# 'd_eff_tail_norm_deriv_smooth_5',
# 'd_eff_tail_norm_smooth_5',
# 'duration_large',
# 'duration_large_small',
# 'eig_deriv_smooth_5',
# 'eig_smooth_5',
# 'full_path',
# 'global_state',
# 'global_state_large_state',
# 'global_state_small_large_state',
# 'head_velocity_norm_smooth_5',
# 'hunch',
# 'hunch_large',
# 'hunch_strong',
# 'hunch_weak',
# 'id',
# 'larva_length_deriv_smooth_5',
# 'larva_length_smooth_5',
# 'motion_to_u_tail_head_smooth_5',
# 'motion_to_v_tail_head_smooth_5',
# 'motion_velocity_norm_smooth_5',
# 'n_duration',
# 'n_duration_large',
# 'n_duration_large_small',
# 'nb_action',
# 'nb_action_large',
# 'nb_action_large_small',
# 'neuron',
# 'numero_larva',
# 'numero_larva_num',
# 'pipeline',
# 'proba_global_state',
# 'prod_scal_1',
# 'prod_scal_2',
# 'protocol',
# 'roll',
# 'roll_large',
# 'roll_strong',
# 'roll_weak',
# 'run',
# 'run_large',
# 'run_strong',
# 'run_weak',
# 'small_motion',
# 'start_stop',
# 'start_stop_large',
# 'start_stop_large_small',
# 'stimuli',
# 'stop',
# 'stop_large',
# 'stop_strong',
# 'stop_weak',
# 'straight_and_light_bend_proba',
# 'straight_proba',
# 't',
# 't_start_stop',
# 't_start_stop_large',
# 't_start_stop_large_small',
# 'tail_velocity_norm_smooth_5',
# 'x_center',
# 'x_contour',
# 'x_head',
# 'x_neck',
# 'x_neck_down',
# 'x_neck_top',
# 'x_spine',
# 'x_tail',
# 'y_center',
# 'y_contour',
# 'y_head',
# 'y_neck',
# 'y_neck_down',
# 'y_neck_top',
# 'y_spine',
#  'y_tail']